### ISSUE TITLE
通过网络抓包获取题目及答案

### ISSUE THREAD

**Issue by whiteki08** [ChaosJulien/XiaoYuanKouSuan_Auto#1]
请求地址

https://xyks.yuanfudao.com/leo-game-pk/iphone/math/pk/match

响应内容如下

{"pkIdStr":"608829268486627373","otherUser":{"userId":245599600,"userName":"厉不厉害你坤哥","avatarUrl":"https://leo-online.fbcontent.cn/leo-gallery/1926fe764a6085f.jpg","userPendantUrl":null},"otherWinCount":1,"selfWinCount":3,"targetCostTime":90000,"examVO":{"pkIdStr":"608829268486627373","pointId":22,"pointName":"两三位数的加减法","ruleType":0,"questionCnt":10,"correctCnt":0,"costTime":0,"questions":[{"id":0,"examId":608829268486627373,"content":"80-50=\\square","answer":"30","userAnswer":null,"answers":["30"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":1,"examId":608829268486627373,"content":"93-13=\\square","answer":"80","userAnswer":null,"answers":["80"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":2,"examId":608829268486627373,"content":"69-47=\\square","answer":"22","userAnswer":null,"answers":["22"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":3,"examId":608829268486627373,"content":"79-11=\\square","answer":"68","userAnswer":null,"answers":["68"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":4,"examId":608829268486627373,"content":"82-72=\\square","answer":"10","userAnswer":null,"answers":["10"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":5,"examId":608829268486627373,"content":"214+310=\\square","answer":"524","userAnswer":null,"answers":["524"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":6,"examId":608829268486627373,"content":"626+123=\\square","answer":"749","userAnswer":null,"answers":["749"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":7,"examId":608829268486627373,"content":"260+608=\\square","answer":"868","userAnswer":null,"answers":["868"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":8,"examId":608829268486627373,"content":"875+101=\\square","answer":"976","userAnswer":null,"answers":["976"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"},{"id":9,"examId":608829268486627373,"content":"174+813=\\square","answer":"987","userAnswer":null,"answers":["987"],"status":0,"script":null,"wrongScript":null,"ruleType":"ARITHMETIC"}],"updatedTime":0}}

**Comment by ChaosJulien** [comment]
感谢提供

**Comment by WnoteZZ** [comment]
优秀

**Comment by RWGLQJ** [comment]
这样就可以用重写直接吧答案改成1了

**Comment by kongbai141** [comment]
> 这样就可以用重写直接吧答案改成1了

这个是post返回的没法重写吧

**Comment by wyp010428** [comment]
> > 这样就可以用重写直接吧答案改成1了
> 
> 这个是post返回的没法重写吧

可以重写的，我刚试了一下没问题，稍等发教程

**Comment by kongbai141** [comment]
> > > 这样就可以用重写直接吧答案改成1了
> > 
> > 
> > 这个是post返回的没法重写吧
> 
> 可以重写的，我刚试了一下没问题，稍等发教程

草我懂你意思了，直接改response.body把答案全替换，那确实可以

**Comment by wyp010428** [comment]
> > > > 这样就可以用重写直接吧答案改成1了
> > > 
> > > 
> > > 这个是post返回的没法重写吧
> > 
> > 
> > 可以重写的，我刚试了一下没问题，稍等发教程
> 
> 但想实现0.0s感觉只能拆math/pk/submit请求体的加密了

我把答案库直接改1可行，submit加密了实在懒得搞了

**Comment by hhhhhge** [comment]
关键是有sign签名，有没有大佬破解签名的

**Comment by kongbai141** [comment]
> 关键是有sign签名，有没有大佬破解签名的

只能ida逆so找算法吧，破不动等大佬了

**Comment by MamboJiang** [comment]
但其实这个pk是假的，刚试了下打开飞行模式都能匹配到然后打完一局...甚至对面的做题数还会自己增加

**Comment by hhhhhge** [comment]
https://leo.fbcontent.cn/bh5/leo-web-oral-pk/exercise_656db608f6aad6a7.js

**Comment by hhhhhge** [comment]
应该是来自这个js的加密

**Comment by JiuSanBird** [comment]
一人一句坤哥牛逼来

**Comment by hhhhhge** [comment]
![image](https://github.com/user-attachments/assets/6ec1b046-91a4-4d12-98d8-d654edf0b8ad)

**Comment by hhhhhge** [comment]
export const signUrlIfNeeded = (url: string) => {
  return new Promise<string>(resolve => {
    if (isYuanKouSuan() && greaterThanOrEqualTo('3.42.0') && (url.indexOf('{device}') !== -1 || url.indexOf('{client}') !== -1)) {
      runUniqueApi('requestConfig', {
        path: url,
        trigger: (err: any, res: any) => {
          if (err && err !== 0) {
            resolve(url)
          } else {
            resolve(res.wrappedUrl)
          }
        }
      }, 'LeoSecure')
    } else {
      if (url.indexOf('{device}') !== -1 || url.indexOf('{client}') !== -1) {
        const resultUrl = url.replace('{device}', 'api').replace('{client}', 'api')
        resolve(resultUrl)
      } else {
        resolve(url)
      }
    }
  })
}

**Comment by hhhhhge** [comment]
不知道这个有没有用

**Comment by dfaofeng** [comment]
> 不知道这个有没有用

我刚分析完安卓端的,他是加载libRequestEncoder.so这个文件,调用native String zcvsd1wr2t(String str, String str2, int i11)生成的sign,你那个web链接怎么搞到的

**Comment by kongbai141** [comment]
> > 不知道这个有没有用
> 
> 我刚分析完安卓端的,他是加载libRequestEncoder.so这个文件,调用native String zcvsd1wr2t(String str, String str2, int i11)生成的sign,你那个web链接怎么搞到的

webview远程调试

**Comment by zmrlft** [comment]
我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了

**Comment by hhhhhge** [comment]
> 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了

我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp

**Comment by kongbai141** [comment]
要不拉个群啥的算了,issue交流好麻烦(

**Comment by zmrlft** [comment]
> > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> 
> 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp

一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？

**Comment by ruichenxxx** [comment]
> > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > 
> > 
> > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> 
> 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？

这是一个h5 app吧

**Comment by ruichenxxx** [comment]
> > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > 
> > 
> > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> 
> 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？

用sslunpinning、justtrusme、trustmealready都过不了 抓包检测

**Comment by zmrlft** [comment]
> > > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > > 
> > > 
> > > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> > 
> > 
> > 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？
> 
> 用sslunpinning、justtrusme、trustmealready都过不了 抓包检测

那他们到底是咋抓的包？看来我是真的老了

**Comment by kongbai141** [comment]
> > > > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > > > 
> > > > 
> > > > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> > > 
> > > 
> > > 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？
> > 
> > 
> > 用sslunpinning、justtrusme、trustmealready都过不了 抓包检测
> 
> 那他们到底是咋抓的包？看来我是真的老了

我小黄鸟+justtrusme就能抓到

**Comment by hhhhhge** [comment]
> > > > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > > > 
> > > > 
> > > > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> > > 
> > > 
> > > 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？
> > 
> > 
> > 用sslunpinning、justtrusme、trustmealready都过不了 抓包检测
> 
> 那他们到底是咋抓的包？看来我是真的老了

东西告诉你了，看看b站上的教程就行吧

**Comment by zmrlft** [comment]
> > > > > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > > > > 
> > > > > 
> > > > > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> > > > 
> > > > 
> > > > 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？
> > > 
> > > 
> > > 用sslunpinning、justtrusme、trustmealready都过不了 抓包检测
> > 
> > 
> > 那他们到底是咋抓的包？看来我是真的老了
> 
> 东西告诉你了，看看b站上的教程就行吧

OK谢谢

**Comment by hhhhhge** [comment]
抓包方便逆向烦

**Comment by 1807805822** [comment]
搞不懂·0.00秒的，真就是直接修改数据了吧

**Comment by LingerJAB** [comment]
> > > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > > 
> > > 
> > > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> > 
> > 
> > 一定用lsposed吗？我想问一下小猿口算他是用ssl pinning来防中间人攻击的吗？你说的这个webviewpp是啥？
> 
> 用sslunpinning、justtrusme、trustmealready都过不了 抓包检测

我用的trustmealready过ssl了，justtrusme不能加

> 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了

我用的trustmealready过ssl了，好像justtrusme不能加，我猜测是破坏了混淆的请求类🤔

**Comment by LingerJAB** [comment]
> 搞不懂·0.00秒的，真就是直接修改数据了吧
> 

本地计时的，其实会取整才显示0s

**Comment by Gnlop** [comment]
玩着好好的 为啥现在抓包解析不出答案了 是乱码

**Comment by wyp010428** [comment]
pk场已经加密了，练习场刷速度吧

**Comment by Aintor** [comment]
有没有哥们知道octet-stream怎么解密，坐等逆向

**Comment by xiangshangya** [comment]
> > > > > 我的老天爷哇，我抓包老抓不了，只要一开抓包，他就显示网络错误。我尝试用justtrustme，也失败了，有大佬知道这到底是咋抓到的包吗？求求了孩子我真的要哭死了
> > > > 
> > > > 
> > > > 我来教你，抓包简单，lsposed上算法助手pro，如果要调试再装webviewpp
> > > 
> > > 
> > > 我想问一下小猿口算他是用SSL pinning来防中间人攻击的吗？你说的这个webviewpp是啥？
> > 
> > 
> > 用sslunpinning、justtrusme、trustmealready都过不了 抓包检测
> 
> 那他们到底是咋抓的包？看来我是真的老了

trustMeAlready
