### ISSUE TITLE
老师你没写等于的情况

### ISSUE THREAD

**Issue by ChenRiRin** [ChaosJulien/XiaoYuanKouSuan_Auto#32]
我用[java](https://github.com/ChenRiRin/XiaoYuanAutoForJava)
写上了，先感谢老师的思路，只是我学业忙来不及优化各个地方的延迟了

**Comment by ChenRiRin** [comment]
顺便提一嘴，通过不断回调main()重新启动程序会爆栈

**Comment by ChaosJulien** [comment]
在正常情况下不应该导致爆栈呀，没有递归调用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月13日(周日) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ChaosJulien/XiaoYuanKouSuan_Auto] 老师你没写等于的情况 (Issue #32)




 
顺便提一嘴，通过不断回调main()重新启动程序会爆栈

**Comment by ChaosJulien** [comment]
> 顺便提一嘴，通过不断回调main()重新启动程序会爆栈

在正常情况下不应该导致爆栈，没有递归
