### ISSUE TITLE
位置怎么调整

### ISSUE THREAD

**Issue by miloce** [ChaosJulien/XiaoYuanKouSuan_Auto#7]

**Comment by ttyala** [comment]
我在修改识别区域坐标上出现了问题，识别不出数字，其余坐标正常

**Comment by miloce** [comment]
> 我在修改识别区域坐标上出现了问题，识别不出数字，其余坐标正常

识别范围前一个坐标是识别区域左上角，第二个是识别区域右下角，识别范围可以缩小一点
